### ISSUE TITLE
Git clone issue

### ISSUE THREAD

**Issue by AJAYSINGH1512** [vedants03/Knowledge_Graph_Using_BioBERT#1]
getting issue while cloning repo 
Error downloading object: trained-model/pytorch_model.bin (24804e2): Smudge error: Error downloading trained-model/pytorch_model.bin (24804e24fb942ff046014f964f20b8f1a60ca4e8b60e209f751492d9b054efe0): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to '/home/nexyom/Desktop/kg_biobert/Knowledge_Graph_Using_BioBERT/.git/lfs/logs/20240627T195444.731356055.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: trained-model/pytorch_model.bin: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by vedants03** [comment]
@AJAYSINGH1512 I have removed the trained models from repository as I my git lfs quota is exhausted, you will need to train your own models.

**Comment by RishitJoshi97** [comment]
> getting issue while cloning repo Error downloading object: trained-model/pytorch_model.bin (24804e2): Smudge error: Error downloading trained-model/pytorch_model.bin (24804e24fb942ff046014f964f20b8f1a60ca4e8b60e209f751492d9b054efe0): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> 
> Errors logged to '/home/nexyom/Desktop/kg_biobert/Knowledge_Graph_Using_BioBERT/.git/lfs/logs/20240627T195444.731356055.log'. Use `git lfs logs last` to view the log. error: external filter 'git-lfs filter-process' failed fatal: trained-model/pytorch_model.bin: smudge filter lfs failed warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'

i faced the same issue but i was able to get all files using solution provided here https://stackoverflow.com/a/68113604. Hope this works.

**Comment by RishitJoshi97** [comment]
> > getting issue while cloning repo Error downloading object: trained-model/pytorch_model.bin (24804e2): Smudge error: Error downloading trained-model/pytorch_model.bin (24804e24fb942ff046014f964f20b8f1a60ca4e8b60e209f751492d9b054efe0): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> > Errors logged to '/home/nexyom/Desktop/kg_biobert/Knowledge_Graph_Using_BioBERT/.git/lfs/logs/20240627T195444.731356055.log'. Use `git lfs logs last` to view the log. error: external filter 'git-lfs filter-process' failed fatal: trained-model/pytorch_model.bin: smudge filter lfs failed warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'
> 
> i faced the same issue but i was able to get all files using solution provided here https://stackoverflow.com/a/68113604. Hope this works.

sorry my bad files have been removed.
