### ISSUE TITLE
Evaluation Metrics.

### ISSUE THREAD

**Issue by RishitJoshi97** [vedants03/Knowledge_Graph_Using_BioBERT#2]
First of all thank you for providing model files,due to limited resources i was not able to train a good model.I wanted to evaluate the predictions as done in original work here(https://github.com/smitkiri/ehr-relation-extraction/tree/master/biobert_re).It seems it is done using Track2-evaluate-ver4.py file.I tried to do it but  it requires predictions in same format as in .ann files. If you have produce the results using Track2-evaluate-ver4.py file  can you enlighten me on that please.

**Comment by vedants03** [comment]
I had the same problem too, however I was unable to figure out the solution. I ran the evaluation on test and evaluation dataset and not on gold standard dataset. You can find more information regarding the issue [here](https://github.com/smitkiri/ehr-relation-extraction/issues/27).
